/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vegetableapp;
//import maingui.LandingPage;
import javax.swing.JOptionPane;
import vegetableapp.VegCheckGUI;

/**
 *
 * @author Sophie Quinn
 */
public class VegPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VegPanel.class.getName());

    /**
     * Creates new form VegPanel
     */
    public VegPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonGroup = new javax.swing.ButtonGroup();
        vegetableCareGuideLABEL = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        onionRadioButton = new javax.swing.JRadioButton();
        carrotRadioButton = new javax.swing.JRadioButton();
        potatoRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VegCareText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        harvestGuideText = new javax.swing.JTextArea();
        progressTrackerButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vegetableCareGuideLABEL.setBackground(new java.awt.Color(255, 255, 255));
        vegetableCareGuideLABEL.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        vegetableCareGuideLABEL.setText("Vegetable Care Guide");
        getContentPane().add(vegetableCareGuideLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 220, 30));

        homeButton.setText("Back to Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        onionRadioButton.setBackground(new java.awt.Color(0, 255, 102));
        RadioButtonGroup.add(onionRadioButton);
        onionRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        onionRadioButton.setText("Onions");
        onionRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(onionRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, -1));

        carrotRadioButton.setBackground(new java.awt.Color(0, 255, 102));
        RadioButtonGroup.add(carrotRadioButton);
        carrotRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        carrotRadioButton.setText("Carrots");
        carrotRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrotRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(carrotRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, -1));

        potatoRadioButton.setBackground(new java.awt.Color(0, 255, 102));
        RadioButtonGroup.add(potatoRadioButton);
        potatoRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        potatoRadioButton.setText("Potatoes");
        potatoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potatoRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(potatoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 100, -1));

        VegCareText.setEditable(false);
        VegCareText.setColumns(20);
        VegCareText.setLineWrap(true);
        VegCareText.setRows(5);
        VegCareText.setText("\nSelect one of the options\nbelow to view a guide on\nhow to care for each vegetable.");
        VegCareText.setWrapStyleWord(true);
        VegCareText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(VegCareText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 190, -1));

        harvestGuideText.setEditable(false);
        harvestGuideText.setColumns(20);
        harvestGuideText.setLineWrap(true);
        harvestGuideText.setRows(5);
        harvestGuideText.setText("\nClick the button below for \nthe Vegetable Progress Tracker! \nThis will give you an estimated\nhavest time for your vegetables.\n");
        harvestGuideText.setWrapStyleWord(true);
        harvestGuideText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(harvestGuideText);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 110));

        progressTrackerButton.setBackground(new java.awt.Color(51, 255, 102));
        progressTrackerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        progressTrackerButton.setForeground(new java.awt.Color(0, 0, 0));
        progressTrackerButton.setText("Progress Tracker");
        progressTrackerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressTrackerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(progressTrackerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vegetableapp/imagepkg/OOP vegApp bg2.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        //LandingPage landingGUI = new LandingPage();
        //landingGUI.setVisible(true);
        //dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void onionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionRadioButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Lorem ipsum dolor sit amet, consectetur adipiscing elit,\nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco \nlaboris nisi ut aliquip ex ea commodo consequat. \nDuis aute irure dolor in reprehenderit \nin voluptate velit esse cillum dolore eu fugiat nulla pariatur. \nExcepteur sint occaecat cupidatat non proident, \nsunt in culpa qui officia deserunt mollit anim id est laborum.");
    }//GEN-LAST:event_onionRadioButtonActionPerformed

    private void progressTrackerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressTrackerButtonActionPerformed
        // TODO add your handling code here:
        VegCheckGUI sqGUI2 = new VegCheckGUI();
        sqGUI2.setVisible(true);
        dispose();
    }//GEN-LAST:event_progressTrackerButtonActionPerformed

    private void carrotRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrotRadioButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Lorem ipsum dolor sit amet, consectetur adipiscing elit,\nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco \nlaboris nisi ut aliquip ex ea commodo consequat. \nDuis aute irure dolor in reprehenderit \nin voluptate velit esse cillum dolore eu fugiat nulla pariatur. \nExcepteur sint occaecat cupidatat non proident, \nsunt in culpa qui officia deserunt mollit anim id est laborum.");
    }//GEN-LAST:event_carrotRadioButtonActionPerformed

    private void potatoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potatoRadioButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Lorem ipsum dolor sit amet, consectetur adipiscing elit,\nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco \nlaboris nisi ut aliquip ex ea commodo consequat. \nDuis aute irure dolor in reprehenderit \nin voluptate velit esse cillum dolore eu fugiat nulla pariatur. \nExcepteur sint occaecat cupidatat non proident, \nsunt in culpa qui officia deserunt mollit anim id est laborum.");
    }//GEN-LAST:event_potatoRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VegPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioButtonGroup;
    private javax.swing.JTextArea VegCareText;
    private javax.swing.JLabel bg;
    private javax.swing.JRadioButton carrotRadioButton;
    private javax.swing.JTextArea harvestGuideText;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton onionRadioButton;
    private javax.swing.JRadioButton potatoRadioButton;
    private javax.swing.JButton progressTrackerButton;
    private javax.swing.JLabel vegetableCareGuideLABEL;
    // End of variables declaration//GEN-END:variables
}
